### ISSUE TITLE
Add instructions for how to run in the README.md

### ISSUE THREAD

**Issue by jmontross** [brint/chef-joomla#3]
Is it because I have wrong versions of vagrant and berkshelf or there are other missing steps?  I've used vagrant and chef a lot in the past but am new to berkshelf.  

These two sections would be really nice in the readme.  

dependencies 

set up

**Comment by brint** [comment]
Sorry about that, this commit [6fad6c4ebf](https://github.com/brint/chef-joomla/commit/6fad6c4ebf51c847e579d48b6fa0b484649e8179) should cover those instructions.  Pull requests are welcome if you find tweaks that need to be made.
